#
#spring:
#  application:
#    name: product-service
#  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASS:postgres}
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    ddl-auto: create
#    properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:password@localhost:8761/eureka
#
#
#
# # application:
#  #  name: product-service
# # zipkin:
#  #  tracing:
#   #   endpoint: http://localhost:9411/api/v2/spans
#  #management:
#   # tracing:
#    #  sampling:
#  #      probability: 1.0
#
#   # endpoints:
#    #  web:
#     #   exposure:
#      #    include: prometheus
#
#server:
#  port: 8076
#
#logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#